services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant_moxi_new
    ports:
      - "6336:6336"  # REST API
      - "6337:6334"  # gRPC API
    volumes:
      # - ./qdrant/storage:/qdrant/storage
      - ./qdrant_storage_new:/qdrant/storage #<- products data
      - ./qdrant/snapshots:/qdrant/snapshots
    environment:
      - QDRANT__SERVICE__HTTP_PORT=6336
      - QDRANT__SERVICE__GRPC_PORT=6334
    restart: unless-stopped

  opensearch:
    image: opensearchproject/opensearch:latest
    container_name: opensearch
    environment:
      - discovery.type=single-node
      - DISABLE_SECURITY_PLUGIN=true
    ports:
      - 9200:9200
    volumes:
      - ./opensearch_data:/usr/share/opensearch/data

volumes:
  qdrant_storage_new:
  opensearch-data:
